spring:
  application:
    name: api-gateway

server:
  port: 8080
#  ribbon:
#    eureka:
#      enabled: true

ribbon:
  ReadTimeout: 60000
  connection-timeout: 3000
  eureka:
    enabled: true

zuul:
  prefix: /api
  routes:
    domain-customer:
      path: /domain-customer/**
      serviceId: domain-customer
    domain-accounts:
      path: /domain-accounts/**
      serviceId: domain-accounts


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostanme: localhost

hystrix:
  command:
    default:
      execuation:
        isolation:
          thread:
            timeoutInMilliseconds: 60000